config/routes.rb
Rails.application.routes.draw do
  root 'recurring_events#index'
  resources :recurring_events
end

app/models/recurring_event.rb
# == Schema Information
#
# Table name: recurring_events
#
#  id                  :integer          not null, primary key
#  name                :string(250)      not null
#  start_date          :datetime         not null
#  interval_months     :integer          not null
#  day_of_month        :integer          not null
#  deliver_buffer_days :integer          not null
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class RecurringEvent < ActiveRecord::Base
  validates :name,       presence: true, length: { maximum: 250 }
  validates :start_date, presence: true
  validates :interval_months,     numericality: { greater_than: 0 }
  validates :deliver_buffer_days, numericality: { greater_than_or_equal_to: 0 }
  validates :day_of_month, inclusion: { in: 1..31 }
  
  after_initialize :set_default_values
  
  def next_due_date
    next_four_event_dates.first.due_date
  end
  
  def next_delivery_date
    next_four_event_dates.first.delivery_date
  end
  
  def first_calculated_date
    if day_of_month < start_date.day
      date = start_date + 1.month
      EventDate.new(date.year, date.month, day_of_month)
    else
      EventDate.new(start_date.year, start_date.month, day_of_month)
    end
  end
  
  def next_four_event_dates
    results = []
    calculated_date = first_calculated_date
    until results.count == 4
      dates = EventDates.new(calculated_date, deliver_buffer_days)
      if dates.due_date > Date.today && dates.due_date > start_date
        results << dates
        calculated_date = calculated_date.increment_months(interval_months)
      else
        calculated_date = calculated_date.increment_months
      end
    end
    results
  end
  
  private
    def set_default_values
      self.start_date ||= Date.today
      self.interval_months ||= 1
      self.deliver_buffer_days ||= 0
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recurring_events_controller.rb
class RecurringEventsController < ApplicationController
  def index
    @recurring_events = RecurringEvent.order(created_at: :desc)
      .paginate(page: params[:page], per_page: 50)
  end
  
  def new
    @recurring_event = RecurringEvent.new
  end
  
  def create
    @recurring_event = RecurringEvent.new(recurring_event_params)
    if @recurring_event.save
      flash[:success] = 'Recurring Event Created!'
      redirect_to recurring_event_path(@recurring_event)
    else
      render :new
    end
  end
  
  def show
    @recurring_event = RecurringEvent.find(params[:id])
  end
  
  def edit
    @recurring_event = RecurringEvent.find(params[:id])
    render :new
  end
  
  def update
    @recurring_event = RecurringEvent.find(params[:id])
    if @recurring_event.update_attributes(recurring_event_params)
      flash[:success] = 'Recurring Event Updated!'
      redirect_to recurring_event_path(@recurring_event)
    else
      render :edit
    end
  end
  
  def destroy
    @recurring_event = RecurringEvent.find(params[:id])
    @recurring_event.destroy
    redirect_to recurring_events_path
  end
  
  private
    def recurring_event_params
      params.require(:recurring_event).permit(
        :name, :start_date, :interval_months, :day_of_month, :deliver_buffer_days
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_error_message(obj)
    render('shared/error_messages', object: obj) if obj.errors.any?
  end
end

app/helpers/recurring_events_helper.rb
module RecurringEventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecurringEvents</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "Recurring Events", root_path, id: 'logo' %>
      <ul class="nav nav-pills navbar-right">
        <li><%= link_to '+ Add New Recurring Event', new_recurring_event_path %></li>  
      </ul>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <noscript>
        <div class="alert alert-danger">
          We can do a lot better with JavaScript enabled ...
        </div>
      </noscript>
      <div class="col-md-12">
        <% flash.each do |type, msg| %>
          <div class="alert alert-<%= type %>"><%= msg %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/recurring_events/index.html.erb
<h3 class="page-title">Recurring Events</h3>
<%= will_paginate @polls %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Start Date</th>
      <th>Next Due Date</th>
      <th>Next Delivery Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%- @recurring_events.each do |r| %>
      <tr>
        <td><%= r.name %></td>
        <td><%= r.start_date.strftime('%a, %b %d, %Y') %></td>
        <td><%= r.next_due_date.strftime('%a, %b %d, %Y') %></td>
        <td><%= r.next_delivery_date.strftime('%a, %b %d, %Y') %></td>
        <td>
          <%= link_to 'show', recurring_event_path(r), class: 'btn btn-success' %>
          <%= link_to 'edit', edit_recurring_event_path(r), class: 'btn btn-warning' %>
          <%= link_to 'delete', recurring_event_path(r), class: 'btn btn-danger', method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/recurring_events/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h3 class="page-title">New Recurring Event</h3>
  <hr>
  <%= form_for @recurring_event, html: { class: 'form-horizontal' } do |f| %>
    <%= render_error_message(f.object) %>
    <div class="form-group">
      <%= f.label :name, class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name', autofocus: true %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :start_date, class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.date_field :start_date, class: 'form-control', placeholder: 'Start Date' %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :interval_months, 'Frequency in months', class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.number_field :interval_months, class: 'form-control', min: 1 %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :day_of_month, 'Day of the month', class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.number_field :day_of_month, class: 'form-control', in: 1..31 %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :deliver_buffer_days, 'Number of Buffer Days', class: 'col-md-3 control-label' %>
      <div class="col-md-9">
        <%= f.number_field :deliver_buffer_days, class: 'form-control', min: 0 %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.submit 'Done!', class: 'btn btn-success btn-block' %>
    </div>
  <% end %>
</div>

app/views/recurring_events/show.html.erb
<h3 class="page-title">New Recurring Event</h3>
<h4><%= @recurring_event.name %></h6>
<table class="table">
  <tr>
    <td>Start Date</td>
    <td><%= @recurring_event.start_date.strftime('%a, %b %d, %Y') %></td>
  </tr>
  <tr>
    <td>Number of months between occurrences</td>
    <td><%= @recurring_event.interval_months %></td>
  </tr>
  <tr>
    <td>Day of Month</td>
    <td><%= @recurring_event.day_of_month %></td>
  </tr>
  <tr>
    <td>Number of Buffer Days</td>
    <td><%= @recurring_event.deliver_buffer_days %></td>
  </tr>
</table>

<table class="table">
  <thead>
    <tr>
      <td>Calculated Date</td>
      <td>Delivery Date</td>
      <td>Due Date</td>
    </tr>
  </thead>
  <tbody>
    <%- @recurring_event.next_four_event_dates.each do |dt| %>
      <tr>
        <td><%= dt.calculated_date.strftime('%a, %b %d, %Y') %></td>
        <td><%= dt.delivery_date.strftime('%a, %b %d, %Y') %></td>
        <td><%= dt.due_date.strftime('%a, %b %d, %Y') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
  <div class="col-md-4">
    <%= link_to 'Show All Recurring Events', recurring_events_path, class: 'btn btn-success btn-block' %>
  </div>
  <div class="col-md-4">
    <%= link_to 'edit', edit_recurring_event_path(@recurring_event), class: 'btn btn-warning btn-block' %>
  </div>
  <div class="col-md-4">
    <%= link_to 'delete', recurring_event_path(@recurring_event), class: 'btn btn-danger btn-block', method: :delete %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<div id="error_list">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, 'error') %>
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>